### DISCUSSION TITLE
Issues running Kaneo on Raspberry Pi

### DISCUSSION THREAD

**Discussion by Akos-Kreutz** [usekaneo/kaneo#104] [Q&A] [answered]
Hi!

So I tried out the application locally with the test compose and everything went fine. I use a Raspberry Pi 5 to run my local services and wanted to switch to Kanoe instead of what I'm currently. I modified the compose file with two changes:

- Mounted the volumes to specific paths (the `[PATH]` is just a placeholder for now, it's an actual path locally) on my drive. Just to make sure I tested these changes locally and did not cause any issue.
- Changed the `KANEO_API_URL` so it's pointing the IP of the Raspberry Pi. I found that if I use localhost it will not work as will do this forever: https://pastey.lol/u/chrome_BLPyw64kp4.mp4

```
services:
  backend:
    image: ghcr.io/kaneo-app/api:latest
    environment:
      JWT_ACCESS: "change_me"
      DB_PATH: "/app/apps/api/data/kaneo.db"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
    ports:
      - 1337:1337
    restart: unless-stopped
    volumes:
      - [PATH]:/app/apps/api/data
    depends_on:
      rabbitmq:
        condition: service_healthy

  frontend:
    image: ghcr.io/kaneo-app/web:latest
    environment:
      KANEO_API_URL: "http://192.168.1.3:1337"
    ports:
      - 5173:80
    depends_on:
      - backend
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - [PATH]:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
```

So after changing the `KANEO_API_URL` I'm able to create a new user and login, however the session is not saved. Every time I refresh the page I have to login again. But the more interesting issue, which makes it unusable is that I'm not able to create `workspace` or `project`.  The URL will contain `undefined` instead of the `workspace id` and when creating a project it will say `Not Found` (which I guess is referring to the workspace it wants to create the project in). I also tried to call the `API list endpoint` which listed nothing, meaning couldn't find anything to list.

What puzzles me is the user I create is persisted so that should mean the communication between the services do work.

All the ports are open on the raspberry. 

If you could help that would be highly appreciated, Thank you!
