### DISCUSSION TITLE
Unable to log in

### DISCUSSION THREAD

**Discussion by b-rajiv** [usekaneo/kaneo#296] [Q&A]
Installed using docker, created a few tasks.
This was a few days ago. Currently, not able to log in, get an error message: "invalid credentials". Clicking "Forgot password" does nothing,

Checked that 'kaneo.db' has all the data in it.
Where is the guide to solving out common problems?

**Comment by faeztgh** [comment]
Hi,
Please try with this config: 
(Dont forget to set environment variables)

```
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${KANEO_DB}
      POSTGRES_USER: ${KANEO_DB_USER}
      POSTGRES_PASSWORD: ${KANEO_DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    image: ghcr.io/usekaneo/api:latest
    environment:
      JWT_ACCESS: ${KANEO_JWT_ACCESS}
      DATABASE_URL: "postgresql://${KANEO_DB_USER}:${KANEO_DB_PASSWORD}@postgres:5432/${KANEO_DB}"
    ports:
      - 1337
    depends_on:
      postgres:
        condition: service_started
    restart: unless-stopped

  frontend:
    image: ghcr.io/usekaneo/web:latest
    environment:
      KANEO_API_URL: "https://${BACKEND_HOST}"
    ports:
      - 5173
    depends_on:
      backend:
        condition: service_started
    restart: unless-stopped

volumes:
  postgres_data:
```
