### DISCUSSION TITLE
Install help - Box spins forever on loading screen

### DISCUSSION THREAD

**Discussion by Otterbacher-OtekEng** [usekaneo/kaneo#81] [Q&A]
I'm new to self hosting Docker images and don't fully understand the compose file.  Below is what I have now - thoughts?

My issue is that the web app doesn't load when I go to 0.0.0.0:5173, the kaneo box spins forever.  Portainer is used to run the docker compose script.

Thanks!

```
services:
  backend:
    image: ghcr.io/kaneo-app/api:latest
    environment:
      JWT_ACCESS: "ghp_..."                                                            # Github access token goes here?
      DB_PATH: "/home/scott/Docker/kaneo/kaneo.db"                # Created kaneo folder on hosting computer - Do I need to create kaneo.db?
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
    ports:
      - 1337:1337
    restart: unless-stopped
    volumes:
      - sqlite_data:/home/scott/Docker/kaneo
    depends_on:
      rabbitmq:
        condition: service_healthy

  frontend:
    image: ghcr.io/kaneo-app/web:latest
    environment:
      KANEO_API_URL: "http://localhost:1337"
    ports:
      - 5173:80
    depends_on:
      - backend
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/home/scott/Docker/rabbitmq              # rabbit mq folder created on hosting computer, no files created when kaneo runs
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  sqlite_data:
  rabbitmq_data:
```

**Comment by Dikendev** [comment]
Hello @Otterbacher-OtekEng,

It seems that the API might be trying to connect to RabbitMQ using an incorrect route. Could you please verify that the connection route in your API configuration matches the route of the RabbitMQ instance running in your Docker setup?

Thank you!

**Comment by Dikendev** [comment]
I have fixed this by matching the RabbitMQ route used in the environment variables.

**Comment by Otterbacher-OtekEng** [comment]
By 'RabbitMQ' route do you mean the port?  The port of RABBITMQ_URL is the same as used in the rabbitmq container (5672).

I'm not defining any environmental variables other than what's defined in the compose file - am I missing something?

**Reply by Dikendev** [reply]
my bad, yeah i mean port

**Comment by andrejsshell** [comment]
Hey, I have updated the compose a little bit since last time. Is this still reproducable for you?

**Reply by Zoobdude** [reply]
I'm having issues with it loading infinitely, here's my config:

```
services:
  backend:
    image: ghcr.io/usekaneo/api:latest
    environment:
      JWT_ACCESS: "df76aQ8sEi3q0MbaknWBPbW9XJuUhf3s"
      DB_PATH: "/app/apps/api/data/kaneo.db"
    ports:
      - 1337:1337
    restart: unless-stopped
    volumes:
      - ./data/sqlite_data:/app/apps/api/data

  frontend:
    image: ghcr.io/usekaneo/web:latest
    environment:
      KANEO_API_URL: "https://todo-api.***.com"
    ports:
      - 5173:80
    restart: unless-stopped
```

I have the API URL set correctly
