### ISSUE TITLE
Unable to create tasks in 0.2.0

### ISSUE THREAD

**Issue by alexgutjahr** [usekaneo/kaneo#121]
Hey there, I've updated to the most recent version yesterday, but am now unable to create tasks.

Specifically `POST /task/create` fails with an HTTP 500 and the message `attempt to write a readonly database`.
The database has these permissions on the docker host `-rw-r--r-- 1 root root  84K Mar 24 14:22 kaneo.db`.

I am not sure why this happens; it seems the API is using it's own non-root user so that might explain why it hasn't access to the database and I could grant write permissions to everyone on the db. Alternatively, passing `UID` and `GID` might be sufficient.

**Comment by aacevski** [comment]
Hey, can you share the docker compose? Thank you!

**Comment by alexgutjahr** [comment]
There you go:

```yaml
---
services:
  backend:
    image: ghcr.io/usekaneo/api:latest
    container_name: kaneo-backend
    environment:
      JWT_ACCESS: "<hidden>"
      DB_PATH: "/app/apps/api/data/kaneo.db"
    restart: unless-stopped
    networks:
      - homelab
    volumes:
      - /home/alex/docker/kaneo/data:/app/apps/api/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kaneo-api.rule=Host(`kaneo-api.example.org`)"
      - "traefik.http.routers.kaneo-api.entrypoints=websecure"
      - "traefik.http.routers.kaneo-api.tls=true"
      - "traefik.http.routers.kaneo-api.tls.certresolver=cloudflare"
      - "traefik.http.services.kaneo-api.loadbalancer.server.port=1337"

  frontend:
    image: ghcr.io/usekaneo/web:latest
    container_name: kaneo-frontend
    environment:
      KANEO_API_URL: "https://kaneo-api.example.org"
    restart: unless-stopped
    networks:
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kaneo.rule=Host(`kaneo.example.org`)"
      - "traefik.http.routers.kaneo.entrypoints=websecure"
      - "traefik.http.routers.kaneo.tls=true"
      - "traefik.http.routers.kaneo.tls.certresolver=cloudflare"
      - "traefik.http.services.kaneo.loadbalancer.server.port=80"

networks:
  homelab:
    external: true
```
