### ISSUE TITLE
Identation of codeblock removed after saving

### ISSUE THREAD

**Issue by fsmeets84** [usekaneo/kaneo#179]
The indentation of a codeblock is removed after saving it and reopening the task.

1. Create a new task or open an existing task.
2. Add a code block, for example the docker-compose.yaml of the project
```
services:
  backend:
    image: ghcr.io/usekaneo/api:latest
    environment:
      JWT_ACCESS: "change_me"
      DB_PATH: "/app/apps/api/data/kaneo.db"
    ports:
      - 1337:1337
    restart: unless-stopped
    volumes:
      - sqlite_data:/app/apps/api/data

  frontend:
    image: ghcr.io/usekaneo/web:latest
    environment:
      KANEO_API_URL: "http://localhost:1337"
    ports:
      - 5173:5173
    restart: unless-stopped

volumes:
  sqlite_data:
```
3. Close the task and reopen it. The indentation is now removed.

![Image](https://github.com/user-attachments/assets/72edad6e-5e55-4026-84d7-bfda8f6e7f1c)
