### ISSUE TITLE
Won't stay logged in

### ISSUE THREAD

**Issue by ItsNoted** [usekaneo/kaneo#65]
When i refresh the page it boots me back to the login screen.

```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration

/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/

/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh

10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf

10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version

/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh

/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh

/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh

/docker-entrypoint.sh: Launching /docker-entrypoint.d/env.sh

KANEO_API_URL=http://192.168.1.83:1337
```

**Comment by aacevski** [comment]
Hey! Thank you for opening the first issue 🙌🏼 Currently - this project is still work in progress. However I can help you with this. Most likely the backend and frontend don't have origin from the same site and the cookie isn't valid. 

How are you deploying the application? Is it locally or is it on a server?

Again, thank you so much!

**Comment by ItsNoted** [comment]
Its locally in docker but on a proxmox node. I'm accessing it over network.

**Comment by ItsNoted** [comment]
Nothing?

**Comment by ItsNoted** [comment]
This is my docker compose. How do you propose I do it otherwise? Thanks!

````
ervices:
  backend:
    image: ghcr.io/kaneo-app/api:latest
    environment:
      JWT_ACCESS: "Sce4ghtvbnhyDxCssfWeCvW24"
      DB_PATH: "/app/apps/api/data/kaneo.db"
    ports:
      - 1337:1337
    restart: unless-stopped
    volumes:
      - /docker/kaneo/sqlite_data:/app/apps/api/data

  frontend:
    image: ghcr.io/kaneo-app/web:latest
    environment:
      KANEO_API_URL: "http://192.168.1.83:1337"
    ports:
      - 5173:80
    depends_on:
      - backend
    restart: unless-stopped
```

**Comment by aacevski** [comment]
Since I can see that the frontend and backend are in the same VM and in the same compose, what would happen if you specify that the API_URL to be:
KANEO_API_URL: "http://localhost:1337" 

Let me know if this works.

**Comment by ItsNoted** [comment]
Just does this forever. Loading wheel.

http://pastey.lol/u/chrome_BLPyw64kp4.mp4

**Comment by aacevski** [comment]
Hmm - and is the frontend address you access it http://192.168.1.83:5173?

**Comment by ItsNoted** [comment]
Indeed :)

**Comment by aacevski** [comment]
Okay, I will setup the proxmox instance now on my end and will let you know.

**Comment by aacevski** [comment]
Hey, I sent Hetzner a support ticket to start up a Proxmox instance for me. Hopefully soon they'll be able to start it up and I'll be able to re-create this issue. 

Sorry again for the troubles.

**Comment by encg** [comment]
Having the same issue. Frontend & backend in the same compose file and I can access the app when using the local IP as `KANEO_API_URL`, but I get the login screen when refreshing. Also spinning wheel when using `localhost`.

Debian VM in Proxmox.

**Comment by aacevski** [comment]
Hey y'all. Sorry for being late on the issue. It's been a full month, however I managed to figure out a solution. @ItsNoted with this compose:
```yaml
services:
  backend:
    image: ghcr.io/kaneo-app/api:latest
    environment:
      JWT_ACCESS: "Sce4ghtvbnhyDxCssfWeCvW24"
      DB_PATH: "/app/apps/api/data/kaneo.db"
    ports:
      - 1337:1337
    restart: unless-stopped
    volumes:
      - /docker/kaneo/sqlite_data:/app/apps/api/data

  frontend:
    image: ghcr.io/kaneo-app/web:latest
    environment:
      KANEO_API_URL: "http://192.168.1.83:1337"
    ports:
      - 5173:80
    depends_on:
      - backend
    restart: unless-stopped
```

Now it should work. Let me know!
